name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Deploy to Hugging Face Spaces
        uses: huggingface/huggingface-deploy-action@main
        with:
          repository: ${{ secrets.HF_SPACE_REPO }}
          token: ${{ secrets.HF_TOKEN }}
          files: .  # Upload all files from the working-directory (dist)
          path-in-repo: .  # Deploy to root of Space repo
          repository-type: space
          space-sdk: static
        working-directory: dist  # Run this step inside the dist folder
